const db = require("./db");
const { newId, deriveStatus, toCsv } = require("./utils");

function daysFromNow(days, hours = 0) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(d.getHours() + hours, 0, 0, 0);
  return d.toISOString();
}

// ---------------------------------------------------------------------
// HACKATHONS (primary content)
// ---------------------------------------------------------------------
const hackathons = [
  {
    title: "Google AI Hackathon India 2026",
    organizer: "Google Developer Groups India",
    source: "Unstop",
    sourceUrl: "https://unstop.com",
    description:
      "Build applied-AI products using Gemini APIs. Open to college students across India, teams of 2-4. Mentorship from Google engineers and a shot at the national demo day.",
    startDate: daysFromNow(11),
    endDate: daysFromNow(13),
    registrationDeadline: daysFromNow(2, 3),
    location: "Online",
    mode: "ONLINE",
    eligibility: "College students (any year), teams of 2-4",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: 500000,
    tags: "AI/ML,Open Innovation",
    skills: "Python,Machine Learning,React",
    registrationUrl: "https://unstop.com/hackathons/google-ai-hackathon",
    imageUrl: null,
  },
  {
    title: "Smart India Hackathon 2026 - Software Edition",
    organizer: "Government of India (MoE Innovation Cell)",
    source: "Government Platform",
    sourceUrl: "https://sih.gov.in",
    description:
      "The flagship national hackathon addressing real problem statements from government ministries and industry. Multi-round selection culminating in a 36-hour grand finale.",
    startDate: daysFromNow(45),
    endDate: daysFromNow(47),
    registrationDeadline: daysFromNow(20),
    location: "Multiple cities",
    mode: "HYBRID",
    eligibility: "College students, teams of 6 with 1 mentor",
    teamSizeMin: 6,
    teamSizeMax: 6,
    prizePool: 100000,
    tags: "Open Innovation,Web Development,AI/ML,FinTech,Healthcare",
    skills: "React,Node.js,Python,UI/UX",
    registrationUrl: "https://sih.gov.in/register",
    imageUrl: null,
  },
  {
    title: "HackVerse Pune 2026",
    organizer: "Army Institute of Technology, Pune",
    source: "College Website",
    sourceUrl: "https://aitpune.edu.in",
    description:
      "24-hour offline hackathon hosted on campus. Open theme with special tracks for AI/ML and Cybersecurity. Great for first-time hackathon participants.",
    startDate: daysFromNow(18),
    endDate: daysFromNow(19),
    registrationDeadline: daysFromNow(9),
    location: "Pune",
    mode: "OFFLINE",
    eligibility: "College students, beginner friendly, teams of 2-4",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: 75000,
    tags: "AI/ML,Cybersecurity,Beginner Friendly,College Students",
    skills: "C++,Python,React",
    registrationUrl: "https://aitpune.edu.in/hackverse",
    imageUrl: null,
  },
  {
    title: "Devfolio Web3 Buildathon",
    organizer: "Devfolio",
    source: "Devfolio",
    sourceUrl: "https://devfolio.co",
    description:
      "Build decentralized apps on Ethereum and Polygon. Online, global participation, bounties from multiple Web3 protocols on top of the main prize pool.",
    startDate: daysFromNow(25),
    endDate: daysFromNow(27),
    registrationDeadline: daysFromNow(15),
    location: "Online",
    mode: "ONLINE",
    eligibility: "Open to all developers",
    teamSizeMin: 1,
    teamSizeMax: 4,
    prizePool: 800000,
    tags: "Blockchain/Web3,Open Innovation",
    skills: "Solidity,React,Node.js",
    registrationUrl: "https://devfolio.co/web3-buildathon",
    imageUrl: null,
  },
  {
    title: "HackerEarth FinTech Sprint",
    organizer: "HackerEarth",
    source: "HackerEarth",
    sourceUrl: "https://hackerearth.com",
    description:
      "Design solutions for digital lending, UPI innovation, and financial inclusion. Backed by 3 fintech unicorns as sponsors, with pre-placement interview offers for top teams.",
    startDate: daysFromNow(9),
    endDate: daysFromNow(10),
    registrationDeadline: daysFromNow(1, 6),
    location: "Online",
    mode: "ONLINE",
    eligibility: "College students and early professionals, teams of 2-3",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: 300000,
    tags: "FinTech,Open Innovation",
    skills: "Python,React,Node.js",
    registrationUrl: "https://hackerearth.com/fintech-sprint",
    imageUrl: null,
  },
  {
    title: "Bengaluru Tech Hackathon",
    organizer: "Karnataka Innovation Council",
    source: "Company Website",
    sourceUrl: "https://example.org",
    description:
      "48-hour offline hackathon in Bengaluru's tech corridor focused on healthcare and civic tech. On-site accommodation provided for outstation participants.",
    startDate: daysFromNow(30),
    endDate: daysFromNow(32),
    registrationDeadline: daysFromNow(22),
    location: "Bengaluru",
    mode: "OFFLINE",
    eligibility: "College students and professionals, teams of 3-5",
    teamSizeMin: 3,
    teamSizeMax: 5,
    prizePool: 250000,
    tags: "Healthcare,Open Innovation",
    skills: "React,Python,UI/UX",
    registrationUrl: "https://example.org/bengaluru-hackathon",
    imageUrl: null,
  },
  {
    title: "CyberShield National Hackathon",
    organizer: "Data Security Council of India",
    source: "Unstop",
    sourceUrl: "https://unstop.com",
    description:
      "Cybersecurity-focused hackathon covering threat detection, secure infra, and privacy tooling. Includes a CTF qualifier round before the main build phase.",
    startDate: daysFromNow(14),
    endDate: daysFromNow(15),
    registrationDeadline: daysFromNow(6),
    location: "Online",
    mode: "ONLINE",
    eligibility: "College students, teams of 2-4",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: 150000,
    tags: "Cybersecurity,Open Innovation",
    skills: "Python,C++,Cybersecurity",
    registrationUrl: "https://unstop.com/cybershield",
    imageUrl: null,
  },
  {
    title: "Devpost Global Student Hack",
    organizer: "Devpost",
    source: "Devpost",
    sourceUrl: "https://devpost.com",
    description:
      "Global online hackathon open to students worldwide, with a dedicated India leaderboard track. Wide theme range, judged by industry engineers.",
    startDate: daysFromNow(20),
    endDate: daysFromNow(22),
    registrationDeadline: daysFromNow(12),
    location: "Online",
    mode: "ONLINE",
    eligibility: "College students worldwide, teams of 1-4",
    teamSizeMin: 1,
    teamSizeMax: 4,
    prizePool: 400000,
    tags: "Open Innovation,Web Development,AI/ML",
    skills: "React,Python,Node.js,Machine Learning",
    registrationUrl: "https://devpost.com/global-student-hack",
    imageUrl: null,
  },
  {
    title: "Mumbai FinCity Hack",
    organizer: "Maharashtra FinTech Association",
    source: "Company Website",
    sourceUrl: "https://example.org",
    description:
      "Offline hackathon in Mumbai's financial district tackling insurance-tech and wealth-tech problem statements set by industry partners.",
    startDate: daysFromNow(28),
    endDate: daysFromNow(29),
    registrationDeadline: daysFromNow(19),
    location: "Mumbai",
    mode: "OFFLINE",
    eligibility: "College students, teams of 2-4",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: 180000,
    tags: "FinTech,Open Innovation",
    skills: "React,Node.js,Python",
    registrationUrl: "https://example.org/mumbai-fincity-hack",
    imageUrl: null,
  },
  {
    title: "Hyderabad HealthTech Hackathon",
    organizer: "Telangana Health Innovation Hub",
    source: "Government Platform",
    sourceUrl: "https://example.org",
    description:
      "Focused on accessible healthcare tech for tier-2/3 India. Hybrid format with a remote qualifier and an on-site final in Hyderabad.",
    startDate: daysFromNow(35),
    endDate: daysFromNow(37),
    registrationDeadline: daysFromNow(24),
    location: "Hyderabad",
    mode: "HYBRID",
    eligibility: "College students and healthcare professionals, teams of 2-5",
    teamSizeMin: 2,
    teamSizeMax: 5,
    prizePool: 220000,
    tags: "Healthcare,AI/ML",
    skills: "Python,Machine Learning,React",
    registrationUrl: "https://example.org/hyderabad-healthtech",
    imageUrl: null,
  },
  {
    title: "Chennai Open Source Hack Weekend",
    organizer: "FOSS United Chennai",
    source: "College Website",
    sourceUrl: "https://example.org",
    description:
      "A weekend of contributing to real open-source projects, judged on meaningful merged contributions rather than a from-scratch build. Very beginner friendly.",
    startDate: daysFromNow(8),
    endDate: daysFromNow(9),
    registrationDeadline: daysFromNow(4),
    location: "Chennai",
    mode: "OFFLINE",
    eligibility: "Open to all, individuals or teams up to 3",
    teamSizeMin: 1,
    teamSizeMax: 3,
    prizePool: 40000,
    tags: "Open Innovation,Beginner Friendly,Web Development",
    skills: "React,Python,Node.js",
    registrationUrl: "https://example.org/chennai-oss-weekend",
    imageUrl: null,
  },
  {
    title: "Delhi NCR EdTech Hackathon",
    organizer: "Ministry of Education Innovation Cell",
    source: "Government Platform",
    sourceUrl: "https://example.org",
    description:
      "Build tools that improve access to quality education in India. Offline finale in Delhi with cash prizes plus incubation support for top 3 teams.",
    startDate: daysFromNow(40),
    endDate: daysFromNow(42),
    registrationDeadline: daysFromNow(28),
    location: "Delhi",
    mode: "OFFLINE",
    eligibility: "College students, teams of 2-4",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: 300000,
    tags: "Open Innovation,Web Development,AI/ML",
    skills: "React,Python,Node.js,UI/UX",
    registrationUrl: "https://example.org/delhi-edtech-hack",
    imageUrl: null,
  },
  {
    title: "Jaipur Beginner's Hackathon",
    organizer: "Rajasthan Student Developer Community",
    source: "College Website",
    sourceUrl: "https://example.org",
    description:
      "Explicitly designed for first-time hackers. Mentors on-site the whole time, relaxed 12-hour format, no team required to register (team formation happens on day 1).",
    startDate: daysFromNow(6),
    endDate: daysFromNow(6),
    registrationDeadline: daysFromNow(0, 20),
    location: "Jaipur",
    mode: "OFFLINE",
    eligibility: "College students, beginner friendly, individuals welcome",
    teamSizeMin: 1,
    teamSizeMax: 4,
    prizePool: 25000,
    tags: "Beginner Friendly,College Students,Open Innovation",
    skills: "C++,Python,React",
    registrationUrl: "https://example.org/jaipur-beginners-hack",
    imageUrl: null,
  },
  {
    title: "Ahmedabad Manufacturing-Tech Hackathon",
    organizer: "Gujarat Industries Association",
    source: "Company Website",
    sourceUrl: "https://example.org",
    description:
      "Industry 4.0 themed hackathon: IoT, predictive maintenance, and supply-chain optimization for manufacturing. Strong industry mentorship and internship pipeline.",
    startDate: daysFromNow(33),
    endDate: daysFromNow(34),
    registrationDeadline: daysFromNow(23),
    location: "Ahmedabad",
    mode: "OFFLINE",
    eligibility: "Engineering students, teams of 3-4",
    teamSizeMin: 3,
    teamSizeMax: 4,
    prizePool: 160000,
    tags: "Open Innovation,AI/ML",
    skills: "Python,C++,Machine Learning",
    registrationUrl: "https://example.org/ahmedabad-manufacturing-hack",
    imageUrl: null,
  },
  {
    title: "Kolkata Creative-Tech Hack",
    organizer: "Bengal Startup Federation",
    source: "Unstop",
    sourceUrl: "https://unstop.com",
    description:
      "Blends design and engineering — media, gaming, and creative-AI tracks. Offline event with a strong UI/UX judging component.",
    startDate: daysFromNow(24),
    endDate: daysFromNow(25),
    registrationDeadline: daysFromNow(14),
    location: "Kolkata",
    mode: "OFFLINE",
    eligibility: "College students, teams of 2-4",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: 90000,
    tags: "AI/ML,Web Development,Open Innovation",
    skills: "React,UI/UX,Python",
    registrationUrl: "https://unstop.com/kolkata-creative-tech",
    imageUrl: null,
  },
  {
    title: "National Student Blockchain Challenge",
    organizer: "NASSCOM",
    source: "Unstop",
    sourceUrl: "https://unstop.com",
    description:
      "Nationwide online hackathon on blockchain applications beyond crypto — supply chain, identity, and public records. Strong resume value from NASSCOM branding.",
    startDate: daysFromNow(16),
    endDate: daysFromNow(17),
    registrationDeadline: daysFromNow(7),
    location: "Online",
    mode: "ONLINE",
    eligibility: "College students, teams of 2-4",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: 350000,
    tags: "Blockchain/Web3,Open Innovation",
    skills: "Solidity,React,Node.js",
    registrationUrl: "https://unstop.com/nasscom-blockchain",
    imageUrl: null,
  },
  {
    title: "Pune Women in Tech Hackathon",
    organizer: "SheBuilds Pune Chapter",
    source: "Company Website",
    sourceUrl: "https://example.org",
    description:
      "Hackathon and mentorship track for women and non-binary developers, open theme, offline in Pune with a dedicated resume/portfolio review booth.",
    startDate: daysFromNow(21),
    endDate: daysFromNow(22),
    registrationDeadline: daysFromNow(13),
    location: "Pune",
    mode: "OFFLINE",
    eligibility: "Women and non-binary developers, students and professionals",
    teamSizeMin: 1,
    teamSizeMax: 4,
    prizePool: 120000,
    tags: "Open Innovation,Web Development,Beginner Friendly",
    skills: "React,Python,UI/UX",
    registrationUrl: "https://example.org/pune-shebuilds",
    imageUrl: null,
  },
  {
    title: "Global Climate-Tech Hackathon (India Chapter)",
    organizer: "ClimateAction.tech",
    source: "Devpost",
    sourceUrl: "https://devpost.com",
    description:
      "Part of a global climate-tech hackathon series. India chapter runs fully online with local mentors from climate-focused startups.",
    startDate: daysFromNow(38),
    endDate: daysFromNow(40),
    registrationDeadline: daysFromNow(29),
    location: "Online",
    mode: "ONLINE",
    eligibility: "Open to all, teams of 1-4",
    teamSizeMin: 1,
    teamSizeMax: 4,
    prizePool: 260000,
    tags: "Open Innovation,AI/ML",
    skills: "Python,React,Machine Learning",
    registrationUrl: "https://devpost.com/climate-tech-india",
    imageUrl: null,
  },
];

// ---------------------------------------------------------------------
// CODING CONTESTS (secondary content)
// ---------------------------------------------------------------------
const contests = [
  {
    title: "Codeforces Round 987 (Div. 2)",
    organizer: "Codeforces",
    source: "Codeforces",
    sourceUrl: "https://codeforces.com",
    description: "Standard Div. 2 rated round, 5-6 problems, 2 hour duration.",
    startDate: daysFromNow(2, 5),
    endDate: daysFromNow(2, 7),
    registrationDeadline: daysFromNow(2, 5),
    location: "Online",
    mode: "ONLINE",
    eligibility: "Open to all, individual",
    teamSizeMin: 1,
    teamSizeMax: 1,
    prizePool: null,
    tags: "Competitive Programming",
    skills: "C++,DSA",
    registrationUrl: "https://codeforces.com/contests",
    difficulty: "Intermediate",
    durationMinutes: 120,
  },
  {
    title: "CodeChef Starters 145",
    organizer: "CodeChef",
    source: "CodeChef",
    sourceUrl: "https://codechef.com",
    description: "Weekly rated contest for all divisions, beginner-friendly first problems.",
    startDate: daysFromNow(4, 8),
    endDate: daysFromNow(4, 10),
    registrationDeadline: daysFromNow(4, 8),
    location: "Online",
    mode: "ONLINE",
    eligibility: "Open to all, individual",
    teamSizeMin: 1,
    teamSizeMax: 1,
    prizePool: null,
    tags: "Competitive Programming",
    skills: "C++,DSA",
    registrationUrl: "https://codechef.com/contests",
    difficulty: "Beginner",
    durationMinutes: 180,
  },
  {
    title: "LeetCode Weekly Contest 421",
    organizer: "LeetCode",
    source: "LeetCode",
    sourceUrl: "https://leetcode.com",
    description: "4-problem weekly rated contest, classic LeetCode format.",
    startDate: daysFromNow(3, 10),
    endDate: daysFromNow(3, 11),
    registrationDeadline: daysFromNow(3, 10),
    location: "Online",
    mode: "ONLINE",
    eligibility: "Open to all, individual",
    teamSizeMin: 1,
    teamSizeMax: 1,
    prizePool: null,
    tags: "Competitive Programming",
    skills: "Python,DSA",
    registrationUrl: "https://leetcode.com/contest",
    difficulty: "Intermediate",
    durationMinutes: 90,
  },
  {
    title: "AtCoder Beginner Contest 385",
    organizer: "AtCoder",
    source: "AtCoder",
    sourceUrl: "https://atcoder.jp",
    description: "Beginner-oriented rated contest, great for building fundamentals.",
    startDate: daysFromNow(5, 6),
    endDate: daysFromNow(5, 8),
    registrationDeadline: daysFromNow(5, 6),
    location: "Online",
    mode: "ONLINE",
    eligibility: "Open to all, individual",
    teamSizeMin: 1,
    teamSizeMax: 1,
    prizePool: null,
    tags: "Competitive Programming",
    skills: "C++,DSA",
    registrationUrl: "https://atcoder.jp/contests",
    difficulty: "Beginner",
    durationMinutes: 100,
  },
  {
    title: "GeeksforGeeks Weekly Coding Contest",
    organizer: "GeeksforGeeks",
    source: "GeeksforGeeks",
    sourceUrl: "https://geeksforgeeks.org",
    description: "Weekly contest with a mix of easy-to-hard DSA problems.",
    startDate: daysFromNow(6, 9),
    endDate: daysFromNow(6, 11),
    registrationDeadline: daysFromNow(6, 9),
    location: "Online",
    mode: "ONLINE",
    eligibility: "Open to all, individual",
    teamSizeMin: 1,
    teamSizeMax: 1,
    prizePool: 10000,
    tags: "Competitive Programming",
    skills: "C++,DSA",
    registrationUrl: "https://geeksforgeeks.org/contests",
    difficulty: "Intermediate",
    durationMinutes: 120,
  },
];

function insert(items, type) {
  const insertStmt = db.prepare(`
    INSERT INTO events (
      id, title, organizer, source, sourceUrl, type, description, imageUrl,
      startDate, endDate, registrationDeadline, location, mode,
      eligibility, teamSizeMin, teamSizeMax, prizePool, tags, skills,
      registrationUrl, status, difficulty, durationMinutes
    ) VALUES (
      @id, @title, @organizer, @source, @sourceUrl, @type, @description, @imageUrl,
      @startDate, @endDate, @registrationDeadline, @location, @mode,
      @eligibility, @teamSizeMin, @teamSizeMax, @prizePool, @tags, @skills,
      @registrationUrl, @status, @difficulty, @durationMinutes
    )
  `);

  for (const item of items) {
    const event = {
      difficulty: null,
      durationMinutes: null,
      imageUrl: null,
      sourceUrl: null,
      prizePool: null,
      ...item,
      id: newId("evt"),
      type,
    };
    event.status = deriveStatus(event);
    insertStmt.run(event);
  }
}

function seed() {
  db.exec("DELETE FROM saved_events; DELETE FROM events; DELETE FROM user_profiles;");

 

  // A default demo profile so match scoring has something to show
  // before real auth/onboarding exists (Phase 2).
  const insertProfile = db.prepare(`
    INSERT INTO user_profiles (
      id, name, college, year, city, state, skills, interests,
      modePreference, experienceLevel, preferredTeamSize
    ) VALUES (
      @id, @name, @college, @year, @city, @state, @skills, @interests,
      @modePreference, @experienceLevel, @preferredTeamSize
    )
  `);
  insertProfile.run({
    id: "demo-user",
    name: "Yash",
    college: "Army Institute of Technology, Pune",
    year: "2nd Year",
    city: "Pune",
    state: "Maharashtra",
    skills: toCsv(["Python", "C++", "React", "DSA"]),
    interests: toCsv(["AI/ML", "Web Development", "Open Innovation"]),
    modePreference: "ANY",
    experienceLevel: "INTERMEDIATE",
    preferredTeamSize: 3,
  });

  const count = db.prepare("SELECT COUNT(*) AS c FROM events").get().c;
    console.log(`Seeded ${count} events (0 mock — hackathons come from Devpost/Unstop, contests come from Codeforces, all live) and 1 demo profile.`);
}

seed();
